//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASAL
    {
        public CASAL()
        {
            this.GRUPO = new HashSet<GRUPO>();
            this.GRUPO1 = new HashSet<GRUPO>();
            this.PARTICIPANTE = new HashSet<PARTICIPANTE>();
        }
    
        public int IDCASAL { get; set; }
        public int IDMARIDO { get; set; }
        public int IDESPOSA { get; set; }
        public int FUNCAO_ATUAL { get; set; }
        public string UF { get; set; }
        public string CIDADE { get; set; }
        public string BAIRRO { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CEP { get; set; }
    
        public virtual FUNCAO FUNCAO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        public virtual PESSOA PESSOA1 { get; set; }
        public virtual ICollection<GRUPO> GRUPO { get; set; }
        public virtual ICollection<GRUPO> GRUPO1 { get; set; }
        public virtual ICollection<PARTICIPANTE> PARTICIPANTE { get; set; }
    }
}
