//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        public GRUPO()
        {
            this.PARTICIPANTE = new HashSet<PARTICIPANTE>();
        }
    
        public int IDGRUPO { get; set; }
        public int LIDER { get; set; }
        public Nullable<int> LIDER_EM_TREINAMENTO { get; set; }
        public string UF { get; set; }
        public string CIDADE { get; set; }
        public string BAIRRO { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CEP { get; set; }
        public int SEMESTRE { get; set; }
        public int ANO { get; set; }
        public int TIPOGRUPO { get; set; }
    
        public virtual CASAL CASAL { get; set; }
        public virtual CASAL CASAL1 { get; set; }
        public virtual TIPOGRUPO TIPOGRUPO1 { get; set; }
        public virtual ICollection<PARTICIPANTE> PARTICIPANTE { get; set; }
    }
}
