//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCPSEntities : DbContext
    {
        public dbCPSEntities()
            : base("name=dbCPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CASAL> CASAL { get; set; }
        public DbSet<FUNCAO> FUNCAO { get; set; }
        public DbSet<GRUPO> GRUPO { get; set; }
        public DbSet<PARTICIPANTE> PARTICIPANTE { get; set; }
        public DbSet<PESSOA> PESSOA { get; set; }
        public DbSet<TIPOGRUPO> TIPOGRUPO { get; set; }
    }
}
