//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public int IDPARTICIPANTE { get; set; }
        public int IDCASAL { get; set; }
        public int IDGRUPO { get; set; }
        public int FUNCAO_NA_EPOCA { get; set; }
    
        public virtual CASAL CASAL { get; set; }
        public virtual FUNCAO FUNCAO { get; set; }
        public virtual GRUPO GRUPO { get; set; }
    }
}
