//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA
    {
        public PESSOA()
        {
            this.CASAL = new HashSet<CASAL>();
            this.CASAL1 = new HashSet<CASAL>();
        }
    
        public int IDPESSOA { get; set; }
        public int NUMERO_DE_MEMBRO { get; set; }
        public string SEXO { get; set; }
        public string NOME { get; set; }
        public System.DateTime DATANASC { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string TELEFONE_FIXO { get; set; }
        public string CELULAR { get; set; }
        public string E_MAIL { get; set; }
    
        public virtual ICollection<CASAL> CASAL { get; set; }
        public virtual ICollection<CASAL> CASAL1 { get; set; }
    }
}
