//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOGRUPO
    {
        public TIPOGRUPO()
        {
            this.GRUPO = new HashSet<GRUPO>();
        }
    
        public int IDTIPOGRUPO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<GRUPO> GRUPO { get; set; }
    }
}
